import React from 'react'

const Projects = () => {
  return (
     <div>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id fuga ipsum officiis, aperiam iure consequatur error reprehenderit ipsam quisquam, cum vel amet expedita, repellendus repudiandae velit voluptatibus at. Quisquam, est atque dolore necessitatibus dolorum, accusantium nostrum doloribus rem perferendis a tempore. Est, repellat. Ratione maxime magnam rerum tempore ipsa ex temporibus quod similique! Quaerat distinctio voluptatibus non facere sed, nesciunt dicta perspiciatis modi totam eos ullam. Beatae nam ullam quasi voluptatibus veritatis eum rem inventore reiciendis consequuntur laborum nulla, fuga unde dolorum in aspernatur iusto corporis eveniet assumenda deserunt ipsum atque laboriosam eaque mollitia ab. Quaerat est eos corrupti neque, accusamus deleniti, in magnam fugit maiores pariatur facilis vero blanditiis. Magni voluptatibus voluptatem nesciunt possimus aut fuga blanditiis repellat sunt fugiat nemo dolores deserunt quasi quam maiores odit, dicta eaque repudiandae esse. Eveniet corrupti aut voluptatem itaque possimus perspiciatis modi soluta! Perspiciatis temporibus exercitationem minus rem molestias id sit maiores odio deserunt labore laudantium facilis nisi dolores ipsum recusandae, perferendis ad tempore atque deleniti ullam maxime nesciunt impedit. Natus dolor, quisquam ipsa debitis repellat perspiciatis ratione nostrum est similique excepturi consequuntur unde placeat impedit ab vel reiciendis doloremque quo officiis porro voluptatem tenetur asperiores ad totam! Commodi, illo. Excepturi, esse?
   Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id fuga ipsum officiis, aperiam iure consequatur error reprehenderit ipsam quisquam, cum vel amet expedita, repellendus repudiandae velit voluptatibus at. Quisquam, est atque dolore necessitatibus dolorum, accusantium nostrum doloribus rem perferendis a tempore. Est, repellat. Ratione maxime magnam rerum tempore ipsa ex temporibus quod similique! Quaerat distinctio voluptatibus non facere sed, nesciunt dicta perspiciatis modi totam eos ullam. Beatae nam ullam quasi voluptatibus veritatis eum rem inventore reiciendis consequuntur laborum nulla, fuga unde dolorum in aspernatur iusto corporis eveniet assumenda deserunt ipsum atque laboriosam eaque mollitia ab. Quaerat est eos corrupti neque, accusamus deleniti, in magnam fugit maiores pariatur facilis vero blanditiis. Magni voluptatibus voluptatem nesciunt possimus aut fuga blanditiis repellat sunt fugiat nemo dolores deserunt quasi quam maiores odit, dicta eaque repudiandae esse. Eveniet corrupti aut voluptatem itaque possimus perspiciatis modi soluta! Perspiciatis temporibus exercitationem minus rem molestias id sit maiores odio deserunt labore laudantium facilis nisi dolores ipsum recusandae, perferendis ad tempore atque deleniti ullam maxime nesciunt impedit. Natus dolor, quisquam ipsa debitis repellat perspiciatis ratione nostrum est similique excepturi consequuntur unde placeat impedit ab vel reiciendis doloremque quo officiis porro voluptatem tenetur asperiores ad totam! Commodi, illo. Excepturi, esse?</div>
  )
}

export default Projects